defmodule Cleanalign.Repo.Migrations.InitialMigration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:email, :citext, null: false)
      add(:hashed_password, :text, null: false)
    end

    create(unique_index(:users, [:email], name: "users_unique_email_index"))

    create table(:user_tokens, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:token, :text, null: false)
      add(:type, :text, null: false)
      add(:expires_at, :utc_datetime, null: false)

      add(
        :user_id,
        references(:users, column: :id, name: "user_tokens_user_id_fkey", type: :uuid),
        null: false
      )
    end

    create table(:user_roles, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(:user_id, references(:users, column: :id, name: "user_roles_user_id_fkey", type: :uuid),
        primary_key: true,
        null: false
      )

      add(:role_id, :uuid, null: false, primary_key: true)
    end

    create table(:roles, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:user_roles) do
      modify(
        :role_id,
        references(:roles, column: :id, name: "user_roles_role_id_fkey", type: :uuid)
      )
    end

    create(
      unique_index(:user_roles, [:user_id, :role_id], name: "user_roles_unique_user_role_index")
    )

    alter table(:roles) do
      add(:name, :text, null: false)
    end

    create(unique_index(:roles, [:name], name: "roles_unique_name_index"))
  end

  def down do
    drop_if_exists(unique_index(:roles, [:name], name: "roles_unique_name_index"))

    alter table(:roles) do
      remove(:name)
    end

    drop_if_exists(
      unique_index(:user_roles, [:user_id, :role_id], name: "user_roles_unique_user_role_index")
    )

    drop(constraint(:user_roles, "user_roles_role_id_fkey"))

    alter table(:user_roles) do
      modify(:role_id, :uuid)
    end

    drop(table(:roles))

    drop(constraint(:user_roles, "user_roles_user_id_fkey"))

    drop(table(:user_roles))

    drop(constraint(:user_tokens, "user_tokens_user_id_fkey"))

    drop(table(:user_tokens))

    drop_if_exists(unique_index(:users, [:email], name: "users_unique_email_index"))

    drop(table(:users))
  end
end
